---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-label
  label:
    app: nginx
    env: dev
    version: v1.1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
 apiVersion: v1
 kind: Pod
 metadata:
   name: nginx-pod-label 2
   label:
    app: nginx
    env: qv
    version: v1.1
  spec:
    containers:
     - name: nginx
       image: nginx:1.14.2
       ports:
         - containerPort: 80



    