---
apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  labels:
    app: ngnix-pod-labels
    env: dev
    release: v1.1
spec:
  containers:
    - name: ngnix
      image: ngnix:1.14.1
      ports:
        - containerPort: 80
          protocol: TCP


apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod
  labels:
    app: ngnix-pod-labels1
    env: qv
    release: v1.1
spec:
  containers:
    - name: ngnix
      image: ngnix:1.14.1
      ports:
        - containerPort: 8080
          protocol: TCP
