---
apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  label:
    app: ngnix-pod-label
    env: dev
    release: v1.1
spec:
  containers:
    - name: ngnix
      image: ngnix:1.14.1
      ports:
        - containersPorts: 80
          protocol: TCP


apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod
  label:
    app: ngnix-pod-label1
    env: qv
    release: v1.1
spec:
  containers:
    - name: ngnix
      image: ngnix:1.14.1
      ports:
        - containersPorts: 80
          protocol: TCP
